
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 21 15:54:36 CST 2020
//----------------------------------------------------

package analisis.comprobaciones;

import java_cup.runtime.Symbol;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Fri Aug 21 15:54:36 CST 2020
  */
public class AnalizadorSintacticoC extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AnalizadorSintacticoC() {super();}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoC(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoC(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\012\000\002\002\004\000\002\002\003\000\002\002" +
    "\003\000\002\006\002\000\002\002\005\000\002\005\003" +
    "\000\002\005\003\000\002\005\003\000\002\003\003\000" +
    "\002\004\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\015\000\010\003\005\004\011\005\006\001\002\000" +
    "\004\002\000\001\002\000\010\004\ufffe\005\ufffe\006\ufffe" +
    "\001\002\000\004\002\ufff8\001\002\000\004\002\uffff\001" +
    "\002\000\004\002\012\001\002\000\004\002\ufff9\001\002" +
    "\000\004\002\001\001\002\000\010\004\016\005\015\006" +
    "\014\001\002\000\004\002\ufffa\001\002\000\004\002\ufffb" +
    "\001\002\000\004\002\ufffc\001\002\000\004\002\ufffd\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\015\000\010\002\007\003\003\004\006\001\001\000" +
    "\002\001\001\000\004\006\012\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\005\016\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintacticoC$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintacticoC$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintacticoC$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private int tipo;
    

    public void setTipo(int tipo){
        this.tipo = tipo;
    }

    public int getTipo(){
        return tipo;
    }
    
    private Symbol s;
    public void syntaxError(Symbol s){
        this.s = s;
    }
    public Symbol getS(Symbol s){
        return this.s = s;
    }

    public void setAccion(String tipo,String mensaje,String accion){
            System.out.println(tipo+"         "+mensaje);
        }

    public void syntax_error(Symbol s){
            
            if(s!=null){
                //Error e = new Error((String) s.value, "Sintactico", "Error Sintaxis token: " + s.right + " " + s.left + " " + s.value, s.right, s.left);
            
                //escribirErrores(e);
                //setAccion("ERROR","Error Sintaxis token: " + (s.right+1) + " " + (s.left+1) + " " + s.value, "");
            }
    }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalizadorSintacticoC$actions {


    private int tipo;

  private final AnalizadorSintacticoC parser;

  /** Constructor */
  CUP$AnalizadorSintacticoC$actions(AnalizadorSintacticoC parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintacticoC$do_action(
    int                        CUP$AnalizadorSintacticoC$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintacticoC$parser,
    java.util.Stack            CUP$AnalizadorSintacticoC$stack,
    int                        CUP$AnalizadorSintacticoC$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSintacticoC$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintacticoC$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // ids_may ::= ID_MAY 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoC$result = parser.getSymbolFactory().newSymbol("ids_may",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoC$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // ids_min ::= ID_MIN 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoC$result = parser.getSymbolFactory().newSymbol("ids_min",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoC$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // er ::= ERR 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoC$result = parser.getSymbolFactory().newSymbol("er",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoC$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // er ::= ID_MAY 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoC$result = parser.getSymbolFactory().newSymbol("er",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoC$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // er ::= ID_MIN 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoC$result = parser.getSymbolFactory().newSymbol("er",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoC$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INICIO ::= error NT$0 er 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoC$stack.elementAt(CUP$AnalizadorSintacticoC$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.elementAt(CUP$AnalizadorSintacticoC$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.elementAt(CUP$AnalizadorSintacticoC$top-2)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoC$stack.elementAt(CUP$AnalizadorSintacticoC$top-2)).value;

              CUP$AnalizadorSintacticoC$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.elementAt(CUP$AnalizadorSintacticoC$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoC$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // NT$0 ::= 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoC$stack.peek()).value;
parser.syntax_error((Symbol)e); tipo = 0; parser.setTipo(tipo);
              CUP$AnalizadorSintacticoC$result = parser.getSymbolFactory().newSymbol("NT$0",4, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoC$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INICIO ::= ids_may 
            {
              Object RESULT =null;
		tipo = 2; parser.setTipo(tipo);
              CUP$AnalizadorSintacticoC$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoC$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= ids_min 
            {
              Object RESULT =null;
		tipo = 1; parser.setTipo(tipo);
              CUP$AnalizadorSintacticoC$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoC$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.elementAt(CUP$AnalizadorSintacticoC$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.elementAt(CUP$AnalizadorSintacticoC$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoC$stack.elementAt(CUP$AnalizadorSintacticoC$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintacticoC$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.elementAt(CUP$AnalizadorSintacticoC$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoC$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintacticoC$parser.done_parsing();
          return CUP$AnalizadorSintacticoC$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

