
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 21 15:54:36 CST 2020
//----------------------------------------------------

package analisis.comprobaciones;

/** CUP generated class containing symbol constants. */
public class SimbolosC {
  /* terminals */
  public static final int ERR = 4;
  public static final int error = 1;
  public static final int ID_MAY = 3;
  public static final int ID_MIN = 2;
  public static final int EOF = 0;
}

