/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import lalr.lectura.Accion;

/**
 *
 * @author LENOVO-PC
 */
public class VentanaPila extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPila
     */
    public VentanaPila() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    
    public void llenarPila(ArrayList<Accion> listaAcciones){
        DefaultTableModel modeloPila = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }  
            };
        modeloPila.addColumn("PILA");
        modeloPila.addColumn("SIMBOLO");
        modeloPila.addColumn("CADENA");
        modeloPila.addColumn("ACCION");
        
        tablaPila.setModel(modeloPila);
        String [] datos = new String[4];
        
        for (int i = 0; i < listaAcciones.size(); i++) {
            datos[0] = listaAcciones.get(i).getTextoPila();
            datos[1] = listaAcciones.get(i).getTextoSimbolo();
            datos[2] = listaAcciones.get(i).getTextoEntrada();
            datos[3] = listaAcciones.get(i).getTextoAccion();
            modeloPila.addRow(datos);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPila = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaPila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPila);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tablaPila;
    // End of variables declaration//GEN-END:variables
}
