
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 31 17:41:17 CST 2020
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int BETA = 23;
  public static final int NUMERO = 3;
  public static final int SEPARACION = 11;
  public static final int INTERROGACION = 20;
  public static final int DOBLE_PUNTO = 6;
  public static final int NOMBRE = 15;
  public static final int LLAVES_C = 41;
  public static final int LLAVES_A = 40;
  public static final int CUALQUIER_SIM = 42;
  public static final int DOS_PUNTOS = 8;
  public static final int CORCHETE_C = 25;
  public static final int CORCHETE_A = 24;
  public static final int ASTERISCO = 21;
  public static final int IDENTIFICADOR = 2;
  public static final int IGUAL = 33;
  public static final int NUM_VERSION = 7;
  public static final int IGNORAR = 34;
  public static final int LETRA = 5;
  public static final int TAB_RESERV = 30;
  public static final int VERSION = 16;
  public static final int GUION = 28;
  public static final int PUNTO_COMA = 9;
  public static final int EOF = 0;
  public static final int COMENTARIO_C = 14;
  public static final int COMENTARIO_A = 13;
  public static final int COMILLAS = 32;
  public static final int error = 1;
  public static final int COMA = 38;
  public static final int ESPACIO_BLANCO = 31;
  public static final int NUM_VER = 4;
  public static final int COMENTARIO_SIMPLE = 12;
  public static final int PUNTO = 10;
  public static final int AUTOR = 17;
  public static final int PARENTESIS_C = 27;
  public static final int PARENTESIS_A = 26;
  public static final int EXTENSION = 19;
  public static final int SALTO_LINEA = 39;
  public static final int NO_TERMINAL = 37;
  public static final int TERMINAL = 36;
  public static final int LANZAMIENTO = 18;
  public static final int LINEA = 35;
  public static final int SALTO_RESERV = 29;
  public static final int MAS = 22;
}

